name: modular_localization

description: A tool for generating string localizations.

version: 1.0.0

repository: https://github.com/TiagoLacerda/modular-localization

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
